# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(900, 642)
        Frame.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(Frame)
        self.centralwidget.setAcceptDrops(False)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(48, 20, 811, 552))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LeftLayout = QtWidgets.QVBoxLayout()
        self.LeftLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.LeftLayout.setSpacing(7)
        self.LeftLayout.setObjectName("LeftLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Nurse = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Nurse.setObjectName("Nurse")
        self.horizontalLayout_2.addWidget(self.Nurse)
        self.OT = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.OT.setAcceptDrops(False)
        self.OT.setObjectName("OT")
        self.horizontalLayout_2.addWidget(self.OT)
        self.LeftLayout.addLayout(self.horizontalLayout_2)
        self.Image = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Image.setAcceptDrops(False)
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("src/results.png"))
        self.Image.setScaledContents(True)
        self.Image.setObjectName("Image")
        self.LeftLayout.addWidget(self.Image)
        self.progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.LeftLayout.addWidget(self.progressBar)
        self.horizontalLayout.addLayout(self.LeftLayout)
        self.RightLayout = QtWidgets.QVBoxLayout()
        self.RightLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.RightLayout.setContentsMargins(3, -1, -1, -1)
        self.RightLayout.setObjectName("RightLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.RunButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.RunButton.setObjectName("RunButton")
        self.verticalLayout.addWidget(self.RunButton)
        self.StopButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.StopButton.setObjectName("StopButton")
        self.verticalLayout.addWidget(self.StopButton)
        self.SaveDataButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.SaveDataButton.setObjectName("SaveDataButton")
        self.verticalLayout.addWidget(self.SaveDataButton)
        self.SaveImageButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.SaveImageButton.setObjectName("SaveImageButton")
        self.verticalLayout.addWidget(self.SaveImageButton)
        self.QuitButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.QuitButton.setFlat(False)
        self.QuitButton.setObjectName("QuitButton")
        self.verticalLayout.addWidget(self.QuitButton)
        self.RightLayout.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.IterationLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.IterationLabel.setObjectName("IterationLabel")
        self.gridLayout.addWidget(self.IterationLabel, 2, 0, 1, 1)
        self.IncreaseLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.IncreaseLabel.setObjectName("IncreaseLabel")
        self.gridLayout.addWidget(self.IncreaseLabel, 6, 0, 1, 1)
        self.FinalScoreBox = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.FinalScoreBox.setObjectName("FinalScoreBox")
        self.gridLayout.addWidget(self.FinalScoreBox, 7, 2, 1, 1)
        self.FinalScoreLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.FinalScoreLabel.setObjectName("FinalScoreLabel")
        self.gridLayout.addWidget(self.FinalScoreLabel, 7, 0, 1, 1)
        self.IterationBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.IterationBox.setMaximum(100000)
        self.IterationBox.setProperty("value", 100)
        self.IterationBox.setObjectName("IterationBox")
        self.gridLayout.addWidget(self.IterationBox, 2, 2, 1, 1)
        self.AntNumBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.AntNumBox.setMaximum(100000)
        self.AntNumBox.setProperty("value", 100)
        self.AntNumBox.setObjectName("AntNumBox")
        self.gridLayout.addWidget(self.AntNumBox, 4, 2, 1, 1)
        self.AntNumLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.AntNumLabel.setObjectName("AntNumLabel")
        self.gridLayout.addWidget(self.AntNumLabel, 4, 0, 1, 1)
        self.DecayRateLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.DecayRateLabel.setObjectName("DecayRateLabel")
        self.gridLayout.addWidget(self.DecayRateLabel, 5, 0, 1, 1)
        self.IncreaseBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.IncreaseBox.setSingleStep(0.05)
        self.IncreaseBox.setProperty("value", 0.1)
        self.IncreaseBox.setObjectName("IncreaseBox")
        self.gridLayout.addWidget(self.IncreaseBox, 6, 2, 1, 1)
        self.DecayRateBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.DecayRateBox.setMaximum(1.0)
        self.DecayRateBox.setSingleStep(0.05)
        self.DecayRateBox.setProperty("value", 0.7)
        self.DecayRateBox.setObjectName("DecayRateBox")
        self.gridLayout.addWidget(self.DecayRateBox, 5, 2, 1, 1)
        self.RightLayout.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.RightLayout)
        Frame.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Frame)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 27))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        Frame.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Frame)
        self.statusbar.setObjectName("statusbar")
        Frame.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(Frame)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Frame)
        self.QuitButton.clicked.connect(Frame.close)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "ACO"))
        self.Nurse.setText(_translate("Frame", "Nurse"))
        self.OT.setText(_translate("Frame", "OT"))
        self.RunButton.setText(_translate("Frame", "运行"))
        self.StopButton.setText(_translate("Frame", "停止"))
        self.SaveDataButton.setText(_translate("Frame", "保存数据"))
        self.SaveImageButton.setText(_translate("Frame", "保存图片"))
        self.QuitButton.setText(_translate("Frame", "退出"))
        self.IterationLabel.setText(_translate("Frame", "Iteration"))
        self.IncreaseLabel.setText(_translate("Frame", "Increase"))
        self.FinalScoreLabel.setText(_translate("Frame", "FinalScore"))
        self.AntNumLabel.setText(_translate("Frame", "AntNum"))
        self.DecayRateLabel.setText(_translate("Frame", "DecayRate"))
        self.menu.setTitle(_translate("Frame", "文件"))
        self.action.setText(_translate("Frame", "导入配置"))


