# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(784, 546)
        self.centralwidget = QtWidgets.QWidget(Frame)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(550, 20, 160, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RunButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.RunButton.setObjectName("RunButton")
        self.verticalLayout.addWidget(self.RunButton)
        self.StopButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.StopButton.setObjectName("StopButton")
        self.verticalLayout.addWidget(self.StopButton)
        self.SaveDataButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.SaveDataButton.setObjectName("SaveDataButton")
        self.verticalLayout.addWidget(self.SaveDataButton)
        self.SaveImageButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.SaveImageButton.setObjectName("SaveImageButton")
        self.verticalLayout.addWidget(self.SaveImageButton)
        self.QuitButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.QuitButton.setFlat(False)
        self.QuitButton.setObjectName("QuitButton")
        self.verticalLayout.addWidget(self.QuitButton)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(550, 300, 161, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.DecayRateBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.DecayRateBox.setMaximum(100000)
        self.DecayRateBox.setProperty("value", 100)
        self.DecayRateBox.setObjectName("DecayRateBox")
        self.gridLayout.addWidget(self.DecayRateBox, 5, 2, 1, 1)
        self.AntNumLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AntNumLabel.setObjectName("AntNumLabel")
        self.gridLayout.addWidget(self.AntNumLabel, 2, 0, 1, 1)
        self.IterationLable = QtWidgets.QLabel(self.gridLayoutWidget)
        self.IterationLable.setObjectName("IterationLable")
        self.gridLayout.addWidget(self.IterationLable, 4, 0, 1, 1)
        self.FinalScoreBox = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.FinalScoreBox.setObjectName("FinalScoreBox")
        self.gridLayout.addWidget(self.FinalScoreBox, 7, 2, 1, 1)
        self.AntNumBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.AntNumBox.setMaximum(100000)
        self.AntNumBox.setProperty("value", 100)
        self.AntNumBox.setObjectName("AntNumBox")
        self.gridLayout.addWidget(self.AntNumBox, 2, 2, 1, 1)
        self.IterationBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.IterationBox.setMaximum(100000)
        self.IterationBox.setProperty("value", 100)
        self.IterationBox.setObjectName("IterationBox")
        self.gridLayout.addWidget(self.IterationBox, 4, 2, 1, 1)
        self.IncreaseLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.IncreaseLabel.setObjectName("IncreaseLabel")
        self.gridLayout.addWidget(self.IncreaseLabel, 6, 0, 1, 1)
        self.DecayRateLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.DecayRateLabel.setObjectName("DecayRateLabel")
        self.gridLayout.addWidget(self.DecayRateLabel, 5, 0, 1, 1)
        self.FinalScoreLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.FinalScoreLabel.setObjectName("FinalScoreLabel")
        self.gridLayout.addWidget(self.FinalScoreLabel, 7, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox.setSingleStep(0.05)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 6, 2, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(60, 20, 481, 451))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Info = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.Info.setObjectName("Info")
        self.verticalLayout_2.addWidget(self.Info)
        self.ImgBox = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ImgBox.setText("")
        self.ImgBox.setPixmap(QtGui.QPixmap("src/results.png"))
        self.ImgBox.setScaledContents(True)
        self.ImgBox.setWordWrap(False)
        self.ImgBox.setObjectName("ImgBox")
        self.verticalLayout_2.addWidget(self.ImgBox)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        Frame.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Frame)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 784, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        Frame.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Frame)
        self.statusbar.setObjectName("statusbar")
        Frame.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(Frame)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "ACO"))
        self.RunButton.setText(_translate("Frame", "运行"))
        self.StopButton.setText(_translate("Frame", "停止"))
        self.SaveDataButton.setText(_translate("Frame", "保存数据"))
        self.SaveImageButton.setText(_translate("Frame", "保存图片"))
        self.QuitButton.setText(_translate("Frame", "退出"))
        self.AntNumLabel.setText(_translate("Frame", "Iteration"))
        self.IterationLable.setText(_translate("Frame", "AntNum"))
        self.IncreaseLabel.setText(_translate("Frame", "Increase"))
        self.DecayRateLabel.setText(_translate("Frame", "DecayRate"))
        self.FinalScoreLabel.setText(_translate("Frame", "FinalScore"))
        self.menu.setTitle(_translate("Frame", "文件"))
        self.action.setText(_translate("Frame", "导入配置"))

if __name__=="__main__":
    import sys
    app=QtWidgets.QApplication(sys.argv)
    widget=QtWidgets.QMainWindow()
    ui=Ui_Frame()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())
